name: base
channels:
  - defaults
dependencies:
  - git
  - python=3.8.5
  - pip=20.3
  - pip:
      # - -r requirements.txt
      - azure-cli==2.41.0
      - azure-storage-blob==12.14.0
      - azure-identity==1.11.0
      - metaflow==2.7.12
